development:
  sessions:
    default:
      database: mongoid-simple-redis-cache_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: mongoid-simple-redis-cache_test
      hosts:
        - localhost:27017